In [1]:
import pandas as pd
pisa = pd.read_csv('data/pisa2012.csv')

/Users/courtneyfergusonlee/anaconda/envs/DAND/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (15,16,17,21,22,23,24,25,26,30,31,36,37,45,65,123,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
pisa.head()

,Unnamed: 0,CNT,SUBNATIO,STRATUM,OECD,NC,SCHOOLID,STIDSTD,ST01Q01,ST02Q01,...,W_FSTR75,W_FSTR76,W_FSTR77,W_FSTR78,W_FSTR79,W_FSTR80,WVARSTRR,VAR_UNIT,SENWGT_STU,VER_STU
0,1,Albania,80000,ALB0006,Non-OECD,Albania,1,1,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
1,2,Albania,80000,ALB0006,Non-OECD,Albania,1,2,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
2,3,Albania,80000,ALB0006,Non-OECD,Albania,1,3,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
3,4,Albania,80000,ALB0006,Non-OECD,Albania,1,4,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
4,5,Albania,80000,ALB0006,Non-OECD,Albania,1,5,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13

## Goal: Change header names to descriptions
1. Read the pisadict as a pandas file
2. Create a list of header values from the pandas file
3. Make the first list item "F1"
4. Append the remaining names
5. Open the csv file for writing and write the header
6. Delete old header row?

In [3]:
pisa_dict = pd.read_csv('data/pisadict2012.csv')
new_pisa_names = ['NA']
for row in pisa_dict['x']:
    new_pisa_names.append(row)

In [4]:
len(new_pisa_names)

636

In [5]:
pisa.columns = new_pisa_names
pisa.to_csv('data/pisa_updated.csv', chunksize = 20000)

In [6]:
pisa.head()

,NA,Country code 3-character,Adjudicated sub-region code 7-digit code (3-digit country code + region ID + stratum ID),Stratum ID 7-character (cnt + region ID + original stratum ID),OECD country,National Centre 6-digit Code,School ID 7-digit (region ID + stratum ID + 3-digit school ID),Student ID,International Grade,National Study Programme,...,FINAL STUDENT REPLICATE BRR-FAY WEIGHT75,FINAL STUDENT REPLICATE BRR-FAY WEIGHT76,FINAL STUDENT REPLICATE BRR-FAY WEIGHT77,FINAL STUDENT REPLICATE BRR-FAY WEIGHT78,FINAL STUDENT REPLICATE BRR-FAY WEIGHT79,FINAL STUDENT REPLICATE BRR-FAY WEIGHT80,RANDOMIZED FINAL VARIANCE STRATUM (1-80),RANDOMLY ASSIGNED VARIANCE UNIT,Senate weight - sum of weight within the country is 1000,Date of the database creation
0,1,Albania,80000,ALB0006,Non-OECD,Albania,1,1,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
1,2,Albania,80000,ALB0006,Non-OECD,Albania,1,2,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
2,3,Albania,80000,ALB0006,Non-OECD,Albania,1,3,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
3,4,Albania,80000,ALB0006,Non-OECD,Albania,1,4,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
4,5,Albania,80000,ALB0006,Non-OECD,Albania,1,5,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13

In [ ]:
print len(pisa.iloc[0])